export const CAT_BREEDS = [
  '(SRD) Sem raça definida',
  'Persa',
  'Siamês',
  'Maine Coon',
  'Angorá',
  'Sphynx',
  'Ragdoll',
  'British Shorthair',
  'Exótico',
  'Bengal',
  'Norueguês da Floresta',
  'Scottish Fold',
  'Abissínio',
  'Bombay',
  'Birmanês',
  'Burmese',
  'Chartreux',
  'Cornish Rex',
  'Devon Rex',
  'Himalaio',
  'Munchkin',
  'Ocicat',
  'Oriental Shorthair',
  'Russian Blue',
  'Savannah',
  'Selkirk Rex',
  'Somali',
  'Tonquinês',
  'Turkish Angora',
  'Turkish Van',
  'American Curl',
  'American Bobtail',
  'Balinês',
  'Havana Brown',
  'LaPerm',
  'Manx',
];
